version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: dbs
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d blog'" ]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: ./blog
    container_name: django
    command: [ "sh", "./entrypoint.sh" ]
    volumes:
      - ./blog/blog/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./blog/.env.dev
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: ./bot
    container_name: bot
    env_file:
      - ./bot/.env.dev
    ports:
      - 5009:5009

volumes:
  db:

